name: video_url_validator
description: Video URL Validator will validate Video URLs from Popular Video Platforms.
version: 1.0.0-beta.1
homepage: https://github.com/7span/video-url-validator-dart

environment:
  sdk: '>=2.16.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
