name: video_url_validator
description: Video URL Validator will validate Video URLs from Popular Video Platforms.
version: 1.0.4
homepage: https://github.com/7span/video-url-validator-dart
screenshots:
  - description: "Usage: Video URL Validator"
    path: example/screenshots/example.webp

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
